
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikime
  template:
    metadata:
      labels:
        app: wikime
    spec:
      containers:
        - name: app
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always